= Bakiwi Assembly Manuals / Bauanleitungen
Doc Writer <kubisch@informatik.hu-berlin.de>
v0.1, 2020-06-17
:imagesdir: ./img
:toc:

Here you can find the Bakiwi Kit solder and assembly manuals. Depending on your Bakiwi's hardware revision, you have to choose between different versions of the manual. All files of the Bakiwi assembly manuals are under the CREATIVE COMMONS LICENSE CC-BY-NC-SA. All our manuals are written in the fabulous link:https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] markup language.

_Hier finden Sie die Bakiwi Kit Löt- und Montageanleitungen. Abhängig von der Hardwareversion Ihres Bakiwi, müssen Sie zwischen verschiedenen Versionen des Handbuchs wählen. Alle Dateien der Bakiwi-Montageanleitungen befinden sich unter der CREATIVE COMMONS-LIZENZ CC-BY-NC-SA. All unsere Handbücher sind in der fabelhaften link:https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] Markup-Sprache geschrieben._


== Bakiwi Kit

link:https://github.com/ku3i/Bakiwi/blob/master/manual/bakiwi_kit/manual_bakiwi_kit_rev_1_1.adoc [DE - Bauanleitung]

== SO(2)-Walker

link:https://github.com/ku3i/Bakiwi/blob/master/manual/so2walker/readme.adoc[EN - Assembly Manual]



